#+TITLE: Zeromacs Literate Config
#+STARTUP: fold
#+LAST_UPDATED: [2026-07-11 Sat 14:41]

* Introduction

Emacs configuration that tries to use native features and when it doesn't use native features, it tells you why a package is used over native features. The configuration is targeted towards new users.

** UI

When you open Emacs, you see the following
- A menubar
- A toolbar
- A text editing area (A Window/Frame/Buffer)
- Modeline
- Echo area (Minibuffer)

** Menu

The menu is very useful for discovery and learning. It shows the keyboard shortcuts alongside menu label when a keyboard shortcut is available. The important keys are
- M - Alt
- C - Ctrl
- S - Shift

Emacs uses key chords so it is normal to find stuff like
- C-x C-f - Press Ctrl + x and then Ctrl + f
- M-x - Press Alt-x

The M-x shortcut is the most important for beginners, it allows searching from all the options functions at that moment

We will deep dive into learning Emacs once we have a proper setup

** Buffers

Emacs uses a concept of buffers, everything that it displays text is a buffer in Emacs. Think of them like Tabs that shows open file in other editors. Every opened file is a buffer in Emacs too. The difference comes with other things like File browser or Terminal, they are also buffers in Emacs. This is an advantage because all of your existing keyboard shortcuts work the same way in all the buffers.

** Modes

There are two types of Modes in Emacs
- Major mode
- Minor mode

To simplify things

- Major mode is a mode that is always active, a mode is applied to a buffer. If you open a JavaScript file =javascript-mode= will be active, it is a major-mode because only one type of mode can be active on a buffer. A major mode is more than a file type because when you open a Terminal or a File manager, a different major mode is active on those buffers to they behave as expected.
- Minor mode is a mode that adds some functionality and a lot of minor modes can be active at a time. For example, the tool-bar-mode or menu-bar-mode are minor modes. The spelling check or line number options are also minor modes.

** Buffer vs Minibuffer

In Emacs the =buffer= and the =minibuffer= are two major points of interaction and understanding both can help a lot when exploring the ecosystem.

The buffer is what shows the primary content whether it is a file, file manager, terminal, documentation, warning, errors, etc.

The minibuffer is used when user types =M-x= for running commands or =C-x C-f= for =find-file= which is used for opening an existing file or creating new file, opening info about the Emacs functions', variables', etc. Out of the box =minibuffer= only takes a single line but it be made multi-line, keep this in mind.

* Init

Add that to your =~/.config/emacs/init.el= and put this file as =~/.config/emacs/config/org=. This will ensure the config.org is automatically loaded as emacs config.

#+begin_src emacs-lisp :tangle no
;;; init.el --- Entry file for emacs config -*- lexical-binding: t; -*-
(org-babel-load-file
 (expand-file-name "config.org" user-emacs-directory))
#+end_src

* Basic configuration with sane defaults

Emacs defaults are not designed for 2025 so let's fix that first.

** Lexical Binding

This is required, lexical scope is more of a programming topic than emacs, I will skip it here.

#+begin_src emacs-lisp
;;; config.el --- Zeromacs Emacs config -*- lexical-binding: t; -*-
#+end_src

** Load a dark theme

Before anything else, let's use the Emacs' =load-theme= function to set a theme

#+begin_src emacs-lisp :tangle no
(load-theme 'modus-vivendi-tinted)
#+end_src

You can also use *Menu* > *Options* > *Customize Emacs* > *Customize Themes*

If you want a light theme, you can try =modus-operandi-tinted=. You are free to try any other theme as well but I like only these two from the built-in themes.

It is also possible to set third party themes as long as the package is installed.

When Emacs runs as a daemon, the config loads before any graphical frame exists, so =load-theme= applies against a frame-less (or terminal) display and the colors come out wrong in later =emacsclient= frames. The fix is to delay theme loading until the first client frame is created using =server-after-make-frame-hook=, and only load it directly when Emacs is started normally.

#+begin_src emacs-lisp
(use-package nord-theme
  :ensure t
  :config
  (defun my/load-theme (&rest _)
    "Load the theme, resetting any previously enabled themes first."
    (mapc #'disable-theme custom-enabled-themes)
    (load-theme 'nord t))
  (if (daemonp)
      (add-hook 'server-after-make-frame-hook #'my/load-theme)
    (my/load-theme)))
#+end_src

** Disable the toolbar

The toolbar is enabled by default but it is not useful, even for beginners. The toolbar adapts, press C-s to trigger search and the toolbar will change. Press C-g to cancel the search operation. If you hover over the toolbar icons, it will also show the available keyboard shortcuts. Apart from the basic find and replace options I have never found much use of the toolbar so I suggest disabling it.

#+begin_src emacs-lisp
(tool-bar-mode -1)
#+end_src

** Disable the menubar

The menubar in Emacs is really helpful, like the toolbar it also adapts and shows different options when they are available. I keep it enabled so I can see available options and learn them. I highly advice keeping the menubar enabled for the first year of learning, If you still want to disable it, you can do it with

#+begin_src emacs-lisp
(menu-bar-mode -1)
#+end_src

You can always access the menubar with =F10= or ~M-x menu-bar-open~.

** Enable line numbers

We can enable line numbers everywhere with

#+begin_src emacs-lisp :tangle no
(global-display-line-numbers-mode 1)
#+end_src

We can enable relative line numbers by setting the =display-line-numbers-mode= variable. =setq= function is used for setting variables

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

=global-display-line-numbers-mode= enables line numbers everywhere, including the terminal, file browser, help pages and everywhere else and that's not what we want so we will use hooks to enable the line numbers for only the certain modes. Hooks can be used to to set or trigger something conditionally

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'display-line-numbers-mode)
(add-hook 'conf-mode-hook 'display-line-numbers-mode)
#+end_src

Here we have used ='prog-mode-hook=, all the programming languages related modes extend this mode so line numbers will automatically be enabled for all the programming languaets. The ='conf-mode-hook= is for config files, it will also enable the line number for config files.

** Enable recent files

A very basic feature but it becomes really important once we have the full setup and start using multiple projects in Emacs.

#+begin_src emacs-lisp
(recentf-mode 1)
#+end_src

** Enable minibuffer history

Save minibuffer history so it is available when you restart Emacs, it will be used for ranking the auto suggestions when we will setup minibuffer enhancements.

#+begin_src emacs-lisp
(savehist-mode 1)
#+end_src

** Enable line highlight

The line highlight feature can be enabled everywhere with

#+begin_src emacs-lisp :tangle no
(global-hl-line-mode 1)
#+end_src

This will enable it everywhere including terminals like vterm which is annoying because it flickers. Use hooks to enable it for only for programming files, config files and org files.

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'hl-line-mode)
(add-hook 'conf-mode-hook 'hl-line-mode)
(add-hook 'org-mode-hook 'hl-line-mode)
#+end_src

** Enable auto pairs

Electric-pair-mode auto completes the parenthesis, brackets, quotes, etc.

#+begin_src emacs-lisp :tangle yes
(electric-pair-mode 1)
#+end_src

** Enable which key

Shows the available command whey you press a partial key chord like =C-c=

#+begin_src emacs-lisp
(which-key-mode 1)
#+end_src

** Disable scrollbars

This is subjective and I don't like scrollbar in Emacs

#+begin_src emacs-lisp
(scroll-bar-mode -1)
#+end_src

** Enable short answers

In some cases the emacs asks user to type =yes= or =no=, like closing buffer with unsaved content, etc. This setting allows user to press =y= or =n= for the same.

#+begin_src emacs-lisp
(setq use-short-answers t)
#+end_src

** Enable recursive minibuffer

When you want to paste something in Emacs, it uses a list of thins you copied in the past. To access that list we use minibuffer. Now, if you are already in minibuffer (e.g. M-x) and you want to paste something, you can't open another minibuffer. Enabling recursive minibuffer fixes that and you can access minibuffer from minibuffer.

#+begin_src emacs-lisp
(setq enable-recursive-minibuffers t)
#+end_src

** Enable Custom file

Emacs allows changing settings from the menus and saves those settings in a custom file and you can use *Menu* > *Options* > *Customize Emacs* and here you have a lot of options to customize emacs. You can either *Apply* a customization or *Apply and Save*. When you use the *Apply and Save* option, emacs writes the changes to your ~init.el~ file. In practice, this is annoying. We can tell Emacs to use a custom file for customization, the ~custom-file~ variable is used for that, it is an existing variable in Emacs. To set it

#+begin_src emacs-lisp
(setq custom-file (concat user-emacs-directory "custom.el"))
(load custom-file t t)
#+end_src

You can also use =load= function to load your config from different files and make it modular. The =t t= are two parameters to load function, if the =custom.el= is missing it then Emacs won't throw an error and it won't show a warning message either.

** Set Custom Font

Font setting can be confusing in Emacs.

- =default= font: Fallback font
- =fixed-pitch= font: Monospace font
- =variable-pitch= font: Non monospace font

The height is roughly =font size * 10=. Height 120 would be similar to height 12 in modern software.

#+begin_src emacs-lisp
(set-face-attribute 'default nil
		    :family "Iosevka"
		    :height 150
		    :weight 'regular)

;; Monospace font
(set-face-attribute 'fixed-pitch nil
		    :family "Iosevka"
		    :height 150
		    :weight 'regular)

;; Regular font
(set-face-attribute 'variable-pitch nil
		    :family "Fira Sans Book"
		    :height 150
		    :weight 'regular)
#+end_src

** Use system clipboard

By default Emacs doesn't use the system clipboard and that makes copy paste stuff in and out of Emacs impossible, enabling this feature sync the primary keyboard in the system with Emacs clipboard (kill-ring)

#+begin_src emacs-lisp
(setq select-enable-clipboard t)
#+end_src

** Add Battery & Clock to Minibuffer

Add clock to minibuffer

#+begin_src emacs-lisp :tangle yes
(display-battery-mode 1)
(display-time-mode 1)
(setq display-time-and-date t)
#+end_src

** Enable better window management

The ~windmove~ package is a built-in package that provides functions for nativating to windows by direction

#+begin_src emacs-lisp :tangle yes
(windmove-mode 1)
#+end_src

** Always add a newline the end of the file

This will add a new line at the end of the file

#+begin_src emacs-lisp :tangle yes
(setq require-final-newline t)
#+end_src

** Highlight uncommited lines

This will highlight the uncommited changes

#+begin_src emacs-lisp :tangle yes
(use-package diff-hl
  :ensure t
  :hook ((prog-mode conf-mode) . diff-hl-mode))
#+end_src

* Completions

Emacs as built-in support for completions

** Inlay Suggestions

The inlay suggestions features is built into Emacs and can be enabled with

#+BEGIN_SRC emacs-lisp
(global-completion-preview-mode 1)
#+END_SRC

* Org mode

Org mode does a lot of things. This is some sane defaults to make it look modern and have add some improvements

** Indent according to structure

Enable =org-indent-mode= so the org mode nested content shows as indented. This mode throws error if applied globally so it should only be applied in the org mode

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
#+end_src

** Use visual lines

Enable =visual-line-mode= so word-wrap is enabled and =C-a=, =C-e= and other line related operations works on the visible line not the logical line

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'visual-line-mode)
#+end_src

** Modern look

We will use a third party package for it

#+begin_src emacs-lisp :tangle yes
(use-package org-modern
  :ensure t
  :hook ((org-mode . org-modern-mode)
         (org-agenda-finalize . org-modern-agenda)))
#+end_src

Hide the bold, italic, etc markers and make the render superscript and subscript values

#+begin_src emacs-lisp :tangle yes
(setq org-hide-emphasis-markers t)
(setq org-pretty-entities t)
#+end_src

** Set Org Directory

Location of org files, it is used by org capture and org agenda.

#+begin_src emacs-lisp :tangle yes
(setq org-directory "~/Projects/Orgfiles")
#+end_src

** Task management

Save the time when task is marked as done, this can be enabled per org file with =#+STARTUP: logdone=

#+begin_src emacs-lisp :tangle yes
(setq org-log-done 'time)
#+end_src

Recursively scan org files for org agenda

#+begin_src emacs-lisp :tangle yes
(defun my/org-refresh-agenda-files (&rest _)
  "Rescan `org-directory' so new files are included in the agenda."
  (setq org-agenda-files (directory-files-recursively org-directory "\\.org$")))
#+end_src

Run this function before org agenda is loaded

#+begin_src emacs-lisp :tangle yes
(advice-add 'org-agenda
  :before
  #'my/org-refresh-agenda-files)
#+end_src

Add my own org todo keywords

#+begin_src emacs-lisp :tangle yes
(setq org-todo-keywords
  '((sequence "TODO(t)" "IN-PROGRESS(i)" "WAITING(w)" "|" "DONE(d)" "CANCELLED(c)")))
#+end_src

** Last Updated Hook

I like a keeping =#+LAST_UPDATED:= heading in my org files, I add a cusotm function and a save hook to update it.

#+begin_src emacs-lisp :tangle yes
(defun my/org-update-last-updated ()
  (when (eq major-mode 'org-mode)
    (save-excursion
      (goto-char (point-min))
      (when (re-search-forward "^#\\+LAST_UPDATED:" nil t)
        (delete-region (point) (line-end-position))
        (insert " " (format-time-string "[%Y-%m-%d %a %H:%M]"))))))
#+end_src

Add a before save hook to update the =LAST_UPDATED= field

#+begin_src emacs-lisp :tangle yes
(add-hook 'before-save-hook #'my/org-update-last-modified)
#+end_src

** Disable src indentation

#+begin_src emacs-lisp :tangle yes
(add-hook 'org-mode-hook
  (lambda ()
  (electric-indent-local-mode -1)))
#+end_src

** Org capture

Org caputre has a few parts. The core parts are

- Capture templates
- Refile system

*** Setup org caputre notes files

This is the file where captured notes would be saved, this variable is used by the default capture template.

#+begin_src emacs-lisp :tangle yes
(setq org-default-notes-file (concat org-directory "/Notes.org"))
#+end_src

*** Setup capture templates

#+begin_src emacs-lisp :tangle yes
(setq org-capture-templates
  '(("t" "Todo" entry
      (file+headline "Tasks.org" "Inbox")
      "* TODO %?\n  %i\n  %a")

      ("j" "Journal" entry
        (file+olp+datetree "Journal.org")
        "* %?\nEntered on %U\n  %i\n  %a")))
#+end_src

*** Setup a better org-refile system

Org-refile allows moving the tasks from the capture area to the proper place where they belong. By default it only allows moving tasks to top level headings. Change that to 5 levels so when moving a captured item, we get full flexibility of selecting the heading where it belongs

#+begin_src emacs-lisp :tangle yes
(setq org-refile-targets '((org-agenda-files . (:maxlevel . 5))))
#+end_src

The above command may not work if you have files that are recently created or you want to include all the org files. To fix this we will use ~advice-add~ for org-refile, this function will run before org-refile and add add the org files to ~org-agenda-files~ variable.

#+begin_src emacs-lisp :tangle yes
(advice-add 'org-refile
  :before
  #'my/org-refresh-agenda-files)
#+end_src

** Quick Access

It is a good idea to setup quick access

Using a register

#+begin_src emacs-lisp :tangle yes
(set-register ?o (cons 'file (concat org-directory "/Tasks.org")))
#+end_src

It is also possible to set a global keybind to open the primary org file

#+begin_src emacs-lisp :tangle no
(global-set-key (kbd "C-c o") 
  (lambda ()
    (interactive)
      (find-file (concat org-directory "Tasks.org"))))
#+end_src

** Org Babel

#+begin_src emacs-lisp :tangle yes
(setq org-confirm-babel-evaluate nil)
#+end_src

* Packages

This is a list of third party packages as well as first party packages that are very useful for enhancing the UX.

** Introduction

Emacs has packages, they are like plugins. Emacs is an elisp interpreter which means it runs =elisp= code. Most of Emacs is written in =elisp=. In order to customize Emacs, the user only needs to change variables in emacs which we have done a few times with =setq= or by calling functions, we have called many functions with 1 or -1 parameter as well as t parameter which stands for true (Everything non nil is true). In order to change behavior or Emacs, we can add our own functions or extend the built-in functions. Most packages just do that. Emacs is insanely extensible and that's why it is possible to emulate vim in Emacs with evil mode but the extensibility doesn't end there. The possibilities are literally infinite because Emacs is a programmable editor and each user makes changes that suites their own. Now let's look at some of the packages that enhances experience by extending the feature in Emacs or by providing new features.

The basic setup is sufficient for most packages. If extra setup is needed then it is explicitly stated. You can always go to the project documentation to learn more about available options.

=use-package= function is used for using the built-in package manager.

** Completion

The completion packages fall into two categories in Emacs

- In buffer completion
- Minibuffer completion
- Both

*** Minbuffer

**** Vertico

Vertico is a third party package, it is used for enabling vertical list in minibuffer. The name stands for =VERTICal Interactive COmpletion=.

***** Built-in solutions

We can enable the vertical minibuffer with built-in =fido-vertical-mode=.

#+begin_src emacs-lisp :tangle no
(fido-vertical-mode 1)
#+end_src

In the next step we will enable *Marginalia* and =fido-vertical-mode= works fine with it.

Why are we adding *Vertico* if =fido-vertical-mode= already does what we want?

Because, the built-in =fido-vertical-mode= doesn't work with third party completion styles, we will see that in when we will setup *Orderless*.

***** Setup

This basic setup is sufficient.

#+begin_src emacs-lisp
(use-package vertico
  :ensure t
  :init
  (vertico-mode 1))
#+end_src

*** Buffer

These packages are used for inbuffer completion

** Minibuffer Enhancements
*** Marginalia

Marginalia shows help information alongside the list in the minibuffer based on what information is being displayed like

- =M-x= : Shows a description of each function
- =C-x C-f= : Shows file information
- =C-h v= : Shows variable value and description
- =C-h f= : Shows function description

It works with built-in =fido-vertical-mode= as well.

This basic setup is sufficient but it is possible to change what information is shown for file list

#+begin_src emacs-lisp
(use-package marginalia
  :ensure t
  :init
  (marginalia-mode 1))
#+end_src

*** Orderless

Orderless is a completion style package, it adds an =orderless= completion style. Emacs uses completion styles to narrow down a list against a query.

=orderless= completion style allows typing =M-x buffer list= for =M-x list-buffers=, you can even type =buff lis= and still matches. As the name suggest, you can type the part of the input in any order and they will work.

This basic setup is sufficient.

#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles partial-completion))))
  (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring
#+end_src

*** Consult

Consult adds live preview feature as well as a ton of custom functions that starts with =consult-=.

By default, consult adds it's own commands that are a replacement for built-in commands.

If you want to setup consult properly, you should read the consult package documentation after the basic setup

#+begin_src emacs-lisp
(use-package consult
  :ensure t
  :defer t
  :init
  ;; Tweak the register preview for `consult-register-load',
  ;; `consult-register-store' and the built-in commands.  This improves the
  ;; register formatting, adds thin separator lines, register sorting and hides
  ;; the window mode line.
  (advice-add #'register-preview :override #'consult-register-window)
  (setq register-preview-delay 0.5)

  ;; Use Consult to select xref locations with preview
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
  :config
  ;; Optionally configure preview. The default value
  ;; is 'any, such that any key triggers the preview.
  ;; (setq consult-preview-key 'any)
  ;; (setq consult-preview-key "M-.")
  ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
  ;; For some commands and buffer sources it is useful to configure the
  ;; :preview-key on a per-command basis using the `consult-customize' macro.
  (consult-customize
   consult-theme :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep consult-man
   consult-bookmark consult-recent-file consult-xref
   consult-source-bookmark consult-source-file-register
   consult-source-recent-file consult-source-project-recent-file
   ;; :preview-key "M-."
   :preview-key '(:debounce 0.4 any))

  ;; Optionally configure the narrowing key.
  ;; Both < and C-+ work reasonably well.
  (setq consult-narrow-key "<") ;; "C-+"

  ;; Optionally make narrowing help available in the minibuffer.
  ;; You may want to use `embark-prefix-help-command' or which-key instead.
  ;; (keymap-set consult-narrow-map (concat consult-narrow-key " ?") #'consult-narrow-help)
)
#+end_src

** Buffer Completion
*** Corfu

Corfu is a package for buffer completion.

#+begin_src emacs-lisp
(use-package corfu
  :ensure t
  ;; Optional customizations
  ;; :custom
  ;; (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
  ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
  ;; (corfu-preview-current nil)    ;; Disable current candidate preview
  ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
  ;; (corfu-on-exact-match 'insert) ;; Configure handling of exact matches

  ;; Enable Corfu only for certain modes. See also `global-corfu-modes'.
  ;; :hook ((prog-mode . corfu-mode)
  ;;        (shell-mode . corfu-mode)
  ;;        (eshell-mode . corfu-mode))

  :init

  ;; Recommended: Enable Corfu globally.  Recommended since many modes provide
  ;; Capfs and Dabbrev can be used globally (M-/).  See also the customization
  ;; variable `global-corfu-modes' to exclude certain modes.
  (global-corfu-mode 1)

  ;; Enable optional extension modes:
  ;; (corfu-history-mode)
  ;; (corfu-popupinfo-mode)
  )

;; A few more useful configurations...
(use-package emacs
  :custom
  ;; TAB cycle if there are only few candidates
  ;; (completion-cycle-threshold 3)

  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  (tab-always-indent 'complete)

  ;; Emacs 30 and newer: Disable Ispell completion function.
  ;; Try `cape-dict' as an alternative.
  (text-mode-ispell-word-completion nil)

  ;; Hide commands in M-x which do not apply to the current mode.  Corfu
  ;; commands are hidden, since they are not used via M-x. This setting is
  ;; useful beyond Corfu.
  (read-extended-command-predicate #'command-completion-default-include-p))
#+end_src

** Snippets

For beginners it is a good idea to use Yasnippet for both snippet management and a bunch of snippet that comes out of the box.

#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t
  :hook ((prog-mode conf-mode org-mode) . yas-minor-mode))
#+end_src

A collection of snippets

#+begin_src emacs-lisp
(use-package yasnippet-snippets
  :ensure t
  :after yasnippet)
#+end_src

Consult integration for searching and inserting snippets, used by the =SPC p s= keybind

#+begin_src emacs-lisp
(use-package consult-yasnippet
  :ensure t
  :defer t)
#+end_src

** Modal Editing

There are a few modal editing options available for Emacs. =evil-mode= is the most famous one that emulates vim but I prefer using meow over evil. Meow is fundamentally different than =evil-mode= and designed to work with Emacs. 

*** Meow

Meow has something called a keypad mode that is similar to god mode package. Pressing =SPC= starts it
- The first letter input, except x, c, h, m, g will be translated to C-c <key>.

**** Setup

Keyboard layout setup for qwerty

#+begin_src emacs-lisp
(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))
#+end_src

Initialize meow. Set vterm and Custom mode to insert mode by default

#+begin_src emacs-lisp
(use-package meow
  :ensure t
  :config
  (meow-setup)
  (add-to-list 'meow-mode-state-list '(vterm-mode . insert))
  (add-to-list 'meow-mode-state-list '(Custom-mode . insert))
  (meow-global-mode 1)
  (meow-setup-indicator))
#+end_src

**** Treesitter support

The package =meow-tree-sitter= provides support for treesitter with meow.

#+begin_src emacs-lisp
(use-package meow-tree-sitter
  :ensure t
  :after meow
  :config
  (meow-tree-sitter-register-defaults))
#+end_src

** Doom Packges

Doom modeline is a nice modeline package for modeline customization. I am not using it yet because it conflicts with keycast package.

#+begin_src emacs-lisp :tangle no
(use-package doom-modeline
  :ensure t
  :init
  (doom-modeline-mode 1))
#+end_src

** Dirvish

Register dirvish and disable reuse session so multiple dirvish buffers are not created when navigating directories

#+begin_src emacs-lisp :tangle yes
(use-package dired
  :defer t
  :config
  (setq dired-listing-switches
        "-l --almost-all --human-readable --group-directories-first --no-group")
  ;; this command is useful when you want to close the window of `dirvish-side'
  ;; automatically when opening a file
  (put 'dired-find-alternate-file 'disabled nil))
#+end_src

#+begin_src emacs-lisp :tangle yes
(use-package dirvish
  :ensure t
  :init
  (dirvish-override-dired-mode 1)
  :config
  (setq dirvish-reuse-session nil)
  (dirvish-side-follow-mode 1)
  :custom
  (dirvish-quick-access-entries
    '(("h" "~/"                                            "Home")
      ("d" "~/Downloads/"                                  "Downloads")
      ("m" "/mnt/"                                         "Drives")
      ("s" "/ssh:zero-oracle:~"                            "SSH server")
      ("o" "~/Projects/Orgfiles"                           "Org Files")
      ("c" "~/Projects/GitHub/zeromacs/config.org"         "Zeromacs Config")
      ("e" "/sudo:root@localhost:/etc"                     "Modify program settings")
      ("t" "~/.local/share/Trash/files/"                   "TrashCan")))
  :bind
  (("C-c d" . dirvish)
    :map dirvish-mode-map
    ("h" . dired-up-directory)
    ("j" . dired-next-line)
    ("k" . dired-previous-line)
    ("l" . dired-find-file)
    ("TAB" . dirvish-subtree-toggle)
    ("M-s" . dirvish-setup-menu)
    ("F" . dirvish-layout-toggle)
    ("?" . dirvish-dispatch)
    ("i" . dirvish-quick-access)))
#+end_src

Set dirvish attributes

#+begin_src emacs-lisp :tangle yes
(setq dirvish-attributes
  (append 
    '(vc-state subtree-state nerd-icons collapse)))
#+end_src

Dirvish over tramp. This will be a really annoying experience if a Yubikey based SSH key is used that requires touch

#+begin_src emacs-lisp :tangle no
(use-package tramp
  :config
  ;; Enable full-featured Dirvish over TRAMP on ssh connections
  ;; https://www.gnu.org/software/tramp/#Improving-performance-of-asynchronous-remote-processes
  (connection-local-set-profile-variables
   'remote-direct-async-process
   '((tramp-direct-async-process . t)))
  (connection-local-set-profiles
   '(:application tramp :protocol "ssh")
   'remote-direct-async-process)
  ;; Tips to speed up connections
  (setq tramp-verbose 0)
  (setq tramp-chunksize 2000)
  (setq tramp-ssh-controlmaster-options nil))
#+end_src

** Keycast mode

Shows the keybind and the function name when a key is pressed. We set the variable =keycast-mode-line-format= with =%K=. The default is =%k= which shows a GUI button. This change converted that to a TUI botton.

#+begin_src emacs-lisp :tangle yes
(use-package keycast
  :ensure t
  :init
  (setq keycast-mode-line-format "%10s%K%c%r")
  :config
  (keycast-mode-line-mode 1))
#+end_src

** Magit

Enable =visual-line-mode= in all magit buffers so long lines like commit messages and diffs wrap at the window edge instead of running off screen.

#+begin_src emacs-lisp :tangle yes
(use-package magit
  :ensure t
  :hook (magit-mode . visual-line-mode))
#+end_src

** Age encryption

Age is an encryption tool, in this section, we will setup support age encrypted files so they can behave like regular files in Emacs but will remain encrypted on the disk. With the default setup, the user's default =id_rsa= ssh keys will be used for encryption and decryption. I prefer using my own set of keys that are stored on the Yubikey, also using SSH keys requires keys with no passphrase.

#+begin_src emacs-lisp :tangle yes
(use-package age
  :ensure t
  :config
  (age-file-enable)
  :custom
  (age-default-identity
    '("~/.config/age/primary"
      "~/.config/age/yubikey_primary"
      "~/.config/age/yubikey_backup"))
  (age-default-recipient
    '("~/.config/age/primary.pub"
      "~/.config/age/yubikey_primary.pub"
      "~/.config/age/yubikey_backup.pub")))
#+end_src

We can also add visual notification for encryption and decryption, useful when using Yubikeys. Taken from the package README.

#+begin_src emacs-lisp :tangle yes
(require 'notifications)

(defun my/age-notify (msg &optional simple)
  (cond (simple
         (message (format "%s" msg)))
        ((eq system-type 'gnu/linux)
         (notifications-notify
          :title "age.el"
          :body (format "%s" msg)
          :urgency 'low
          :timeout 800))
        ((eq system-type 'darwin)
         (do-applescript
          (format "display notification \"%s\" with title \"age.el\"" msg)))
        (t
         (message (format "%s" msg)))))

(defun my/age-notify-decrypt (&rest args)
  (cl-destructuring-bind (context cipher) args
    (my/age-notify (format "Decrypting %s" (age-data-file cipher)) t)))

(defun my/age-notify-encrypt (&rest args)
  (cl-destructuring-bind (context plain recipients) args
    (my/age-notify (format "Encrypting %s" (age-data-file plain)) t)))

(defun my/age-toggle-decrypt-notifications ()
  (interactive)
  (cond ((advice-member-p #'my/age-notify-decrypt #'age-start-decrypt)
         (advice-remove #'age-start-decrypt #'my/age-notify-decrypt)
         (message "Disabled age decrypt notifications."))
        (t
         (advice-add #'age-start-decrypt :before #'my/age-notify-decrypt)
         (message "Enabled age decrypt notifications."))))

(defun my/age-toggle-encrypt-notifications ()
  (interactive)
  (cond ((advice-member-p #'my/age-notify-encrypt #'age-start-encrypt)
         (advice-remove #'age-start-encrypt #'my/age-notify-encrypt)
         (message "Disabled age encrypt notifications."))
        (t
         (advice-add #'age-start-encrypt :before #'my/age-notify-encrypt)
         (message "Enabled age encrypt notifications."))))

;; we only care about decrypt notifications really
(my/age-toggle-decrypt-notifications)
(my/age-toggle-encrypt-notifications)
#+end_src

** Extra modes for file types

*** KDL mode

#+begin_src emacs-lisp :tangle yes
(use-package kdl-mode
  :ensure t
  :mode "\\.kdl\\'")
#+end_src

*** CSV mode

#+begin_src emacs-lisp :tangle yes
(use-package csv-mode
  :ensure t
  :mode
  "\\.[ct]sv\\'"
  :config
  (setq csv-separators '("," ";" "\t")))
#+end_src

* Custom functions

Custom functions I use to automate repetitive tasks.

** Reload config

When working on the config, emacs has to be rested over and over and over. It is possible to switch to init.el and and eval the buffer to reload the config. We will do exactly that but add a helper method to the config

#+begin_src emacs-lisp
(defun my/reload-config ()
  "Reload emacs config"
  (interactive)
  (load-file (expand-file-name
    "init.el"
    user-emacs-directory)))
#+end_src

** Copy buffer path

#+begin_src emacs-lisp :tangle no
(defun my/yank-buffer-path ()
  (interactive)
)
#+end_src

* Keybinds

I like doom keybinds and try to replicate them as long as they don't interfere with any of the existing keybinds or frequently used keybinds. I am using meow to add keybinds instead of adding them to Emacs

The first letter input, except x, c, h, m, g will be translated to C-c <key>.

#+begin_src emacs-lisp :tangle yes
(meow-leader-define-key
  '("b i" . ibuffer)
  '("b k" . kill-buffer-and-window)
  '("b n" . next-buffer)
  '("b p" . previous-buffer)
  '("f s" . save-buffer)
  '("f p" . (lambda ()
              (interactive)
            (find-file "~/Projects/GitHub/zeromacs/config.org")))
  '("o p" . dirvish-side)
  '("o t" . vterm)
  '("o o" . (lambda ()
            (interactive)
            (find-file (concat org-directory "/Tasks.org"))))

  '("w l" . windmove-right)
  '("w h" . windmove-left)
  '("w j" . windmove-down)
  '("w k" . windmove-up)

  ;; p = preview with consult, not project
  '("p b" . consult-buffer)
  '("p f" . consult-fd)
  '("p l" . consult-line)
  '("p m" . consult-mark)
  '("p p" . consult-org-heading)
  '("p r" . consult-recent-file)
  '("p s" . consult-yasnippet)
  '("p t" . consult-theme)
  '("X"   . scratch-buffer)
)
#+end_src

My own keybinds

#+begin_src emacs-lisp :tangle yes
(keymap-global-unset "C-s")
(keymap-global-unset "C-r")
(keymap-global-set   "C-s C-d" 'consult-line)
(keymap-global-set   "C-s C-r" 'isearch-backward)
(keymap-global-set   "C-s C-s" 'isearch-forward)
(keymap-global-set   "C-c c" 'org-capture)
(which-key-add-key-based-replacements "C-s" "search")
#+end_src

* Tips

** Autocomplete

You can use =M-/= to auto-complete a word that already exists in open buffers. It is really helpful when typing long words, if the correct word is not matched on the first try, press it again and again till you get it right

** Mode Specific Commands

You can use =M-S-x= to search for options that only applies to current major mode, this is really helpful for learning what options are available for current buffer instead of searching all available options.

** Efficient ibuffer

=ibuffer= is a command that shows a list of all buffers, it is interactive so you can mark the buffers with =d= and delete the marked buffers with =x=, really useful for closing a bunch of buffers at once. If you have menu-bar enabled, you can see all the options in the *Menu* > *Operate*

** Editing files with sudo

To edit files with sudo using Emacs, append ~/sudo::~ before the file path and the file will be opened as sudo.

*** Sudo with tramp

=sudo= can be used with tramp to edit files on the remote server as root, I am going to use the server =test-server= as an example here. Enter the following in the find file

#+begin_example
/ssh:user@test-server|sudo::/etc/fstab
#+end_example

** Preview unsaved changes

Use =diff-buffer-with-file= to see what's new in the buffer that's not on the disk. This is specially useful when you run a command by accident and not sure what's changed
